#!/bin/sh

function build {
    # freeze the blog for deployment on render
    source venv/bin/activate
    echo "🥶 freezing the blog..."
    python3 blog.py --build
}

function server {
    # start up the dev server
    source venv/bin/activate
    flask run
}

function shell {
    # start up the flask shell
    source venv/bin/activate
    flask shell
}

function push {
    # push the app to github
    git add -A && git commit && git push
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
